server:
  port: 8081
  hostNameResource: localhost
  hostNameDb:   localhost
  hostNameAuth: localhost

jwt:
  auth:
    converter:
      resource-id: springboot-keycloak-client
      principal-attribute: preferred_username

spring:
  security:
    ignored: /**
    oauth2:
      client:
        registration:
          keycloak:
            client-id: springboot-keycloak-client
            auth-server-url: http://${server.hostNameAuth}:8080/auth
            server-url: http://${server.hostNameAuth}:8080
            authorization-grant-type: authorization_code
            realm: SpringBootKeycloak
            username: user
            password: user
            scope: openid
            bearer-only: true
        provider:
          keycloak:
            issuer-uri:  ${spring.security.oauth2.client.registration.keycloak.server-url}/realms/SpringBootKeycloak
      resourceserver:
        jwt:
          issuer-uri:  ${spring.security.oauth2.client.registration.keycloak.server-url}/realms/SpringBootKeycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
  jpa:
    database: MYSQL
    show-sql: true

  flyway:
    baselineOnMigrate: true
    enabled: true

  datasource:
    url: jdbc:mariadb://${server.hostNameDb}/${spring.datasource.scheme}${spring.datasource.args}
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: "root"
    port: 3306
    scheme: test_cards
    args:  ?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true

  jackson:
    deserialization.fail-on-unknown-properties: true
    date-format: dd-MM-yyyy HH:mm:ss

  logging:
    level:
      org.springframework.web.client.RestTemplate: DEBUG
      org:
        springframework:
          web=DEBUG:

